services:
  - type: web
    name: protfolio-frontend
    env: static
    buildCommand: ./build.sh
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://protfolio-backend-8p47.onrender.com
      - key: VITE_FRONTEND_URL
        value: https://protfolio-frontend-ytfj.onrender.com
      - key: VITE_RENDER
        value: "true"